services:
  web:
    image: php:8.2-apache
    # pensée a changé le nom du container name
    container_name: php-apache-MVC-autoload
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network: